---
name: kanagram
version: 17.08.1
summary: KDE Letter Order Game
description: 'Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct order. There
    is no limit on either time taken, or the amount of attempts to solve the word.
    It features several included word lists, a hints-and-cheats help system, a word
    list editor, and allows for updating and distributing wordlists via KNewStuff.
    The interface is scalable and appropriate for children.'
confinement: strict
grade: stable
apps:
    kanagram:
        command: kf5-launch kanagram
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kanagram
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kanagram:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libkeduvocdocument-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kanagram-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
